hydra:
  searchpath:
    - file://treetune_verl/generation/config
    - file://treetune_verl/tasks/config
    - file://verl/trainer/config

defaults:
  - generation
  - task_definitions@task_defs
  - _self_

trainer:
  project_name: entropy_gen
  experiment_name: gen_entropy

actor_rollout_ref:
  model:
    path: ???
  rollout:
    entropy_top_k: 0  # 0 = full-vocab entropy
    calculate_log_probs: true  # Required for entropy extraction
    agent:
      default_agent_loop: entropy_single_turn_agent

generation:
  custom_manager_cls: treetune_recipe.entropy_gen.agent_loop.EntropyGenerationLoopManager

train_tasks:
  - ${task_defs.hmmt_feb_2025}
